version: '3.1'

services:

  db:
    container_name: pg_gophermart
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_gophermart:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASS}

volumes: 
  pg_gophermart: 
